### ISSUE TITLE
Add semgrep scanning to github actions

### ISSUE THREAD

**Issue by dfarr** [resonatehq/resonate#10]
Include rule to disallow ranging over maps

**Comment by dtornow** [comment]
```
rules:
  - id: range-over-map
    pattern-either:
      - pattern: |
          for $K, $V := range ($MAP : map[$KT]$VT) { ... }
      - pattern: |
          for $K := range ($MAP : map[$KT]$VT) { ... }
    message: Ranging over a map is non deterministic
    languages:
      - go
    severity: ERROR
```
