### ISSUE TITLE
Implement pluggable Authentication (Authn) and Authorization (Authz) for Resonate Server

### ISSUE THREAD

**Issue by avillega** [resonatehq/resonate#551]
## Problem Statement

Currently, the Resonate server currently lacks authentication and authorization besides Basic Auth.

## Solution

Implement token-based authentication (AuthN) and authorization (AuthZ) as separate layers that validate requests after they enter the HTTP server but before they reach the request processing pipeline. JWT validation is the initial implementation, with tokens issued by external authentication services.

### 1. Request Flow

```
Request → [AuthN → AuthZ] → Processing Pipeline → Response
```

### 2. Token Entry Point

Tokens are passed via standard HTTP header:

```
Authorization: Bearer <token>
```

### 3. AuthN Interface (Authentication)

```go
type AuthN interface {
    // Authenticate validates the token and returns identity information
    Authenticate(ctx context.Context, token string) (interface{}, error)
}
```

- Returns interface{} to support different

### 4. AuthZ Interface (Authorization)

```go
type AuthZ interface {
    // Authorize makes access decision based on identity and request
    Authorize(ctx context.Context, token interface{}, request Request) (bool, error)
}
```

- Uses existing Resonate request types

### Configuration example

```
auth:
  enabled: true
  jwt:
    algorithm: RS256
    public_key_path: /path/to/key.pub  # For RS256
    secret: ${JWT_SECRET}              # For HS256
    issuer: auth.example.com
    audience: resonate-api
```
